### ISSUE TITLE
Collision entre Walter et les modules

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#12]
V 0.5.5
Walter disparaît à l'interieur des modèles (par exemple il la tete dans le visiophone quand il tombe, il a le bras dans le roomba, il est dans le modèle du fauteuil quand il s'asseoit) 
Certains modèles traversent Walter

Screencast 
https://drive.google.com/file/d/1aEG8Pd990xDZREAm5xuG_995N51Nz6sa/view?usp=sharing
TC - 2min46

https://drive.google.com/file/d/1GgQNo8YyuHLYHlGyWtNg9x0FXHFR1qnv/view?usp=sharing
TC - 5min50

screenshots 
https://drive.google.com/file/d/1TwVbmcl2OXYezBGWIV0SR6D7x-uMWNzK/view?usp=sharing
https://drive.google.com/file/d/1X-7RYmm75Ugc_Ig8CCphLM0BzYIhyNm-/view?usp=sharing
https://drive.google.com/file/d/1KQsaocGyKH6Ovd5cANW5PVdt18E-gtoQ/view?usp=sharing
https://drive.google.com/file/d/1tHC3Mt3evKQsWNQIPgnEX6f66Ss5sk4t/view?usp=sharing
https://drive.google.com/file/d/1gqauxqiBbRGW0yQ2TKtYODssl2iuE_ac/view?usp=sharing

Device
Iphone 12 Pro
Buil - V 0.5.5

**Comment by Skeloson** [comment]
Le soucis vient du fait que Walter à actuellement un collider unique qui ne suit pas ses animations allongés et d'autre du style.

Un collider a été ajouté sur sa tête (ce qui devrait réglé la tête dans le visio, par exemple). 

Pour les mains, j'ai fais un test mais Walter entre en collision avec beaucoup trop d'objet dans cette configuration. Je vais tenter d'augmenter l'espace qu'il prend sur le navmesh (pour éviter qu'il colle trop au objet pendant le pathfinding, mais ça pourrait amené d'autres problèmes).

Par contre, pour le fauteuil, c'est un autre soucis : dans ce cas-ci, le fauteuil s'est placé sur un objet (et non pas le sol), ce qui n'est pas censé arrivé. Comme l'anim de Walter est prévue pour un fauteuil au sol, ça ne passe pas ^^'.
