### ISSUE TITLE
Distance avec le module quand Walter porte et active

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#13]
il faut une distance fixe avec le module quand Walter active car là il a parfois la ventouse dans le modèle
Pareil quand il porte un module
V 0.5.5

**Comment by Skeloson** [comment]
Le problème se pose avec quel(s) module(s) ?

**Comment by angeliquesimonnet** [comment]
Ca arrive avec des différents, je te mets une capture ici 
Le visiophone quand il active 
https://drive.google.com/file/d/1tHC3Mt3evKQsWNQIPgnEX6f66Ss5sk4t/view?usp=sharing

L'échelle quand il porte 
https://drive.google.com/file/d/15IOaHOuXxKWFDl3YkjSpMq9Hb6_3nw_J/view?usp=sharing

**Comment by Skeloson** [comment]
Pour régler ce bug, il me faut la version définitive de l'échelle, ce qui me permettra de régler la distance à laquelle Walter porte tout les objets et la distance à laquelle il les relâchera.

Si il faut absolument une modif pour le visiophone en attendant, je peux modifier le pivot de cet objet.
