### ISSUE TITLE
Walter disparaît de la scène et ne respawn pas

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#14]
**Describe the bug**
Walter disparaît de la scène (peut-être lié à une collision avec un module)

**Screenshots/Screencast**
TC - 2min47
https://drive.google.com/file/d/1StdY_GPYNhefnhgDKtjIiIMSpm6T8lDK/view?usp=sharing

TC - 3min36
https://drive.google.com/file/d/1IzKY71CxKKumbAYXWxRTWqFryaTfvHGR/view?usp=sharing

**Device:**
 - OS: iPhone12 Pro
 - Build Version V 0.5.5

**Comment by Skeloson** [comment]
Actuellement, ce bug n'apparait que sur iPhone. Il faudrait plus de tester sur différent devices pour déterminer ce qui provoque ce bug.
