### ISSUE TITLE
Regard vers le joueur

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#16]
**Describe the bug**
Quand Walter regarde vers le joueur il ne faut pas seulement qu'il tourne la tete mais aussi qu'il lève la tete vers la position de la caméra. Il manque l'anim ?

**Screenshots/Screencast**
https://drive.google.com/file/d/1DEQZHk74p7Dix_l_ev-AuvHQrQWM-Se2/view?usp=sharing
TC - 7min06

https://drive.google.com/file/d/1GgQNo8YyuHLYHlGyWtNg9x0FXHFR1qnv/view?usp=sharing
TC- 5min06 / 5min12

**Device:**
 - OS: iPhone12 Pro
 - Build Version V 0 .5 . 5

**Comment by Skeloson** [comment]
Je vais tester quelque chose avec le package "rigging" (qui sert à tourner la tête)
