### ISSUE TITLE
Contour blanc autour de la bouche

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#17]
**Describe the bug**
Walter a un contour blanc autour de la bouche

**Device:**
 - OS: iPhone12 Pro
 - Build Version V 0.5.5

**Comment by Skeloson** [comment]
Sur toutes les bouches ?

**Comment by angeliquesimonnet** [comment]
Oui j'ai l'impression mais c'est peut-être lié à la lumière

**Comment by Skeloson** [comment]
Il me faut plus de détail, je n'ai pas vu le soucis de mon coté

**Comment by angeliquesimonnet** [comment]
Je t'ai mis des screenshots ici 
https://drive.google.com/drive/folders/1s63hTQv0bB_0evumwND2VSGwNhTej3vz?usp=sharing

Ca date de la V0.5.7 puisque je ne peux pas aller à après qu'il ait enlevé son casque dans la 5.8
C'est sur iPhone 12Pro
J'ai testé sur Android (P30) et je n'ai pas le problème. Je teste sur un iPhone 8 sans Lidar quand j'ai un nouveau build.

**Comment by angeliquesimonnet** [comment]
J'ai testé aussi sur iPhone 8 sans Lidar j'ai aussi le problème. J'ai l'impression que c'est particulièrement visible quand je m'éloigne de Walter. Quand je suis collée à sa bouche je ne vois pas ce contour. 
A partir de 2min13
https://drive.google.com/file/d/1yTsahuoePo-U4L8x43b3wNw-zeCrBoc3/view?usp=sharing

**Comment by Skeloson** [comment]
Je vais poser la question sur le chan graph, dès fois qu'un artiste aurait déjà eu le soucis et qu'il saurait comment réglé ça rapidement

**Comment by Skeloson** [comment]
J'ai appliqué la solution proposé par Rémi, à tester dans la 0.5.9
