### ISSUE TITLE
Crash de l'apps

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#18]
**Describe the bug**
Après que Walter ait disparu de la scène

**Screenshots/Screencast**
TC-4min14
https://drive.google.com/file/d/1IzKY71CxKKumbAYXWxRTWqFryaTfvHGR/view?usp=sharing

**Device:**
 - OS: iPhone12 Pro
 - Build Version V 0.5.5 

**Additional context**

**Comment by cguillaume44** [comment]
@angeliquesimonnet en cas de crash il faut les logs
Voir avec Remi pour avoir les logs

**Comment by remiengel** [comment]
Thread 28 name:
Thread 28 Crashed:
0   AGXMetalA14                   	0x00000001f34a74a4 -[AGXA14FamilyRenderContext setFragmentTextures:withRange:] + 460 (agxa_render_template.hpp:4032)
1   AGXMetalA14                   	0x00000001f34a7500 -[AGXA14FamilyRenderContext setFragmentTextures:withRange:] + 552 (agxa_render_template.hpp:5290)
2   UnityFramework                	0x000000010538d778 0x104a68000 + 9590648
3   UnityFramework                	0x000000010538d524 0x104a68000 + 9590052
4   UnityFramework                	0x0000000105356570 0x104a68000 + 9364848
5   UnityFramework                	0x0000000105354b38 0x104a68000 + 9358136
6   UnityFramework                	0x0000000105356094 0x104a68000 + 9363604
7   UnityFramework                	0x00000001053567f8 0x104a68000 + 9365496
8   UnityFramework                	0x000000010535c11c 0x104a68000 + 9388316
9   UnityFramework                	0x0000000104e64954 0x104a68000 + 4180308
10  UnityFramework                	0x0000000105356b1c 0x104a68000 + 9366300
11  UnityFramework                	0x00000001052fe054 0x104a68000 + 9003092
12  UnityFramework                	0x00000001053621fc 0x104a68000 + 9413116
13  UnityFramework                	0x00000001052fe908 0x104a68000 + 9005320
14  UnityFramework                	0x00000001052f681c 0x104a68000 + 8972316
15  UnityFramework                	0x0000000104faf664 0x104a68000 + 5535332
16  libsystem_pthread.dylib       	0x00000001f1e739a4 _pthread_start + 148 (pthread.c:891)
17  libsystem_pthread.dylib       	0
[2022-02-07_19-07-20.5362_+0100-aa4af26fd862926f4cc5f1ab7185dbf4b7e78f1a.txt](https://github.com/cguillaume44/WalterIssues/files/8142009/2022-02-07_19-07-20.5362_%2B0100-aa4af26fd862926f4cc5f1ab7185dbf4b7e78f1a.txt)
x00000001f1e72ea0 thread_start + 8

**Comment by remiengel** [comment]
<img width="869" alt="Capture d’écran 2022-03-04 à 14 25 10" src="https://user-images.githubusercontent.com/83295677/156771483-67e4880d-26ba-4f45-94f5-bb2a1a748dbd.png">
