### ISSUE TITLE
Impossible de hold le visiophone

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#19]
**Describe the bug**
On dirait que je ne peux pas le hold par sa face du dessous ?

**Screenshots/Screencast**
https://drive.google.com/file/d/1aEG8Pd990xDZREAm5xuG_995N51Nz6sa/view?usp=sharing
TC - 3min08 à 3min20

**Device:**
 - OS: iPhone12 Pro
 - Build Version V 0.5.5

**Comment by Skeloson** [comment]
À 3m10, il y a une surface verticale qui est crée en AR qui bloque les interactions avec le module
