### ISSUE TITLE
H&P : Walter est dans la machine

### ISSUE THREAD

**Issue by cguillaume44** [cguillaume44/WalterIssues#2]
iPhone 8 - Testflight 0.5(4) - Le 02/02/22 -
screencast https://drive.google.com/file/d/19fGySKD39cOcd7FcujMTCiC0fQUldy7T/view?usp=sharing
TC - 10min18

**Comment by Skeloson** [comment]
Ce bug est potentiellement réglé grâce au roomscan. Je clos le bug tant que nous ne travaillons pas sur les séquence 20 à 29.
