### ISSUE TITLE
Walter disparaît et réapparaît

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#20]
**Describe the bug**
Walter a disparu de la scène sans qu'il n'y ait eu aucune collision. Puis il est réapparu. 

**Screenshots/Screencast**
2min10 à 2min21
https://drive.google.com/file/d/1PETw7r_To2pgTAgatQ7MJQfbYcR53WZa/view?usp=sharing

**Device:**
 - OS: iPhone 12 Pro
 - Build Version V 0.5.5

**Comment by Skeloson** [comment]
Idem que l'issue #14 : Actuellement, ce bug n'apparait que sur iPhone. Il faudrait plus de tester sur différent devices pour déterminer ce qui provoque ce bug.
