### ISSUE TITLE
Module activés qui ne se pose pas sur le sol

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#21]
**Describe the bug**
Quand Walter active certains modules, il s'anime (so'uvre) puis lévite au lieu de se poser sur le sol

**Screenshots/Screencast**
https://drive.google.com/file/d/1rsp3e8I9pWi96jc8v2I8Weuw0K5Pvj1X/view?usp=sharing
TC - 2min41

https://drive.google.com/file/d/1GgQNo8YyuHLYHlGyWtNg9x0FXHFR1qnv/view?usp=sharing
TC - 5min50

https://drive.google.com/file/d/1D_bc5ItPwCu7afZ09PJ1KMDWxNu7puo_/view?usp=sharing
TC - 7min à 7min20

**Device:**
 - OS: iPhone12 Pro
 - Build Version V 0.5.5

**Comment by Skeloson** [comment]
Le drop va être modifier pour ignorer entièrement la physique.

Ce changement sera effectif à partir de la V0.5.9
