### ISSUE TITLE
Walter pousse le module cachette avant de se cacher

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#22]
**Describe the bug**
Walter court au module cachette et l'ejecte avant de se cacher donc il est caché derrière rien, on comprends pas ce qu'il fait

**Screenshots/Screencast**
https://drive.google.com/file/d/1D_bc5ItPwCu7afZ09PJ1KMDWxNu7puo_/view?usp=sharing
TC - 3min49

**Device:**
 - OS: iPhone12Pro
 - Build Version V O.5.5

**Comment by Skeloson** [comment]
Aurais-tu un moyen simple de reproduire ce bug ?

**Comment by angeliquesimonnet** [comment]
J'ai reproduit le bug. J'ai l'impression que ca vient du fait que Walter a un autre module sur son chemin qui le gêne à ce moment là, du coup il pousse le premier module et ça impacte le module-cachette ? 

Screencast
https://drive.google.com/file/d/1UL2XWOG9un_UkFDt4JeV04wxQseODIe2/view?usp=sharing
TC - 1min06 
iPhone 12 Pro V0.5.8

**Comment by Skeloson** [comment]
Est-ce que tu aurais d'autre screencasts où le bug apparait ?

J'ai l'impression qu'ici, c'est dû soit à la collision entre les modules, soit au fait qu'il n'y ai pas assez de place derrière la seconde cachette (j'ai l'impression que Walter prend en compte les fauteuils pour se placer, mais je me trompe peut-être)

**Comment by angeliquesimonnet** [comment]
Dans les 2 screencasts ? 
J'essaye avec le prochain build mais avec le système des 3 cachettes peut-être qu'il peut éviter de choisir un module qu'il a ejecté
