### ISSUE TITLE
Walter reste en suspension après la 2eme chute

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#23]
**Describe the bug**
Walter se met dans la position de chute mais il reste en lévitation sous le vortex

**Screenshots/Screencast**
TC - 2min17
https://drive.google.com/file/d/1UL2XWOG9un_UkFDt4JeV04wxQseODIe2/view?usp=sharing

TC- 2min45
https://drive.google.com/file/d/14B38zlzfpvsscHY88tvK3YbGuZ0bvqoW/view?usp=sharing

**Device:**
 - OS: iPhone12Pro
 - Build Version V0.5.8

**Comment by angeliquesimonnet** [comment]
Sur V.0.5.7
https://drive.google.com/file/d/1DmJjizvYUmn2Hy3m6jXWyOywGqIaiT1X/view?usp=sharing
TC - 4min40

**Comment by remiengel** [comment]
C'est sur la seconde chute à chaque fois visiblement ? On voit bien quand tu envoies un objet sur lui, il remonte puis s'arrête au même endroit, il y a donc clairement quelque chose qui fait une collision et le bloque à ce niveau.

**Comment by angeliquesimonnet** [comment]
Oui c'est la 2de chute à chaque fois

**Comment by angeliquesimonnet** [comment]
2 autres screencasts, c'est quand même très recurrent dans la v0.5.8 

TC 3mi12
https://drive.google.com/file/d/1XS4dGfgNTd9jRMXWD3KfUj1y56MNsyK_/view?usp=sharing

TC2min48
https://drive.google.com/file/d/1wNlNP5LrhEFTaRQ8aTVooE5fCOxUAuXn/view?usp=sharing

**Comment by remiengel** [comment]
Pourras-tu tester dans d'autres pièces ? Il pourrait y avoir quelque chose qui fait croire à la détection ou au LIDAR qu'il y a un plan à cet endroit là (d'où l'intérêt de ne plus avoir de plans dès que possible sur LIDAR).

**Comment by angeliquesimonnet** [comment]
Avec le dernier build le bug ne se reproduit plus
