### ISSUE TITLE
Position de Walter dans le vortex

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#24]
**Describe the bug**
Walter est trop descendu par rapport au vortex
On voit jusqu'à la limite entre la combi et le casque presque

**Screenshots/Screencast**
https://drive.google.com/file/d/14B38zlzfpvsscHY88tvK3YbGuZ0bvqoW/view?usp=sharing
TC - 1min13

**Device:**
 - OS: iPhone 12 Pro
 - Build Version V.0.5.8

**Comment by Skeloson** [comment]
De mon coté, on ne voit bien que jusqu'au bassin de Walter.

Est ce que ça arrive aussi sur Android de ton coté ?

**Comment by Skeloson** [comment]
Potentiellement une collision avec le plafond
