### ISSUE TITLE
Walter chute sur un meuble

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#25]
**Describe the bug**
Walter chute sur un meuble et il n'en redescends pas, il installe toute l'air de jeu là-haut. C'est un pbl car il y a pas assez d'espace, ça ne correspond pas aux zones de jeu prévues. Il faudrait trouver le moyen de le faire descendre, par exemple l'idée du respawn bloqué où il lève les bras et s'enfonce dans le sol et respawn hors cadre dans l'air de jeu fonctionnerait très bien non ? 

**Screenshots/Screencast**
https://drive.google.com/file/d/1DmJjizvYUmn2Hy3m6jXWyOywGqIaiT1X/view?usp=sharing
TC - 5min30

**Device:**
 - OS: iPhone 12 Pro
 - Build Version 0.5.7

**Comment by remiengel** [comment]
C'est un double bug, d'abord il est bloqué par la chute du vortex, puis au moment de se débloquer il se téléporte sur un meuble... commençons par régler le premier bug.
