### ISSUE TITLE
Cachette - module non visible

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#27]
**Describe the bug**
Le module cachette est rentrée dans le meuble (je suppose?) et n'a pas respawn (elle n'est pas detectée comme n'étant plus dans l'air de jeu?) donc Walter se cache là où le module était avant de partir dans le meuble sauf qu'il n'y a rien devant lui. 

**Screenshots/Screencast**
https://drive.google.com/file/d/14B38zlzfpvsscHY88tvK3YbGuZ0bvqoW/view?usp=sharing
TC - 1min08

**Device:**
 - OS: iPhone12Pro
 - Build Version V.0.5.8

**Comment by angeliquesimonnet** [comment]
Un peu le même cas mais pas tout à fait donc je sais pas si je crée une nouvelle issue ? 
Ici le module est en hauteur, du coup Walter se cache à proximité mais c'est pas derrière donc c'est pas compréhensible. 
https://drive.google.com/file/d/1XS4dGfgNTd9jRMXWD3KfUj1y56MNsyK_/view?usp=sharing
TC - 1min46

**Comment by Skeloson** [comment]
Pour le premier soucis : La cachette n'est plus sur le navmesh, Walter veut se cacher derrière, mais théoriquement, le pathfinding l'en empêche, vu que le point sur le navmesh le plus proche de l'objet n'est pas derrière ce dernier.

Le second soucis avait déjà été évoqué, mais il n'y avait pas spécialement de solution qui avait été trouvée
