### ISSUE TITLE
Framerate

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#28]
**Describe the bug**
Il y a beaucoup de baisse de framerate. 
Impossible de manipuler les modules. Les anims sont saccadés. 

**Screenshots/Screencast**
https://drive.google.com/file/d/1_T-05ujpVT-8ObMFoWpTBnUfHridw2n4/view?usp=sharing
FPS counter active à partir de 2min38

**Device:**
 - OS: iPhone12Pro
 - Build Version V0.5.8

**Comment by remiengel** [comment]
Ceci dit : il serait cohérent qu'il y ai plus de baisses de framerates depuis que j'ai passé le Pathfinding sur le mesh et non sur les plans (depuis la 0.5.7), car c'est plus lourd à calculer. Est-ce le cas ?

Chez moi je n'ai pas eu de baisses assez significatives sur la longeur pour que ce soit avéré.
Si c'est lié à ça, j'ai des idées de solutions.
