### ISSUE TITLE
Walter immobile, progression bloquée

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#29]
**Describe the bug**
Le visiophone sonne. Walter se relève. Le visiophone est en hauteur sur le bureau. Walter ne l'aimante pas à distance, il ne se tourne même pas vers le visiophone ou ne s'en approche pas, il se tient immobile. Je descends le visiophone pour le poser sur le sol accessible à Walter, Walter ne réagit toujours pas, il reste immobile. 

**Screenshots/Screencast**
TC - 4min55
https://drive.google.com/file/d/1_T-05ujpVT-8ObMFoWpTBnUfHridw2n4/view?usp=sharing

**Device:**
 - OS: iPhone12Pro
 - Build Version V0.5.8

**Comment by Skeloson** [comment]
J'ai réussis à reproduire le bug : c'était une vieille condition qui aurai dû être retirer après l'intégration de l'animation. Un correctif sera appliqué pour la V0.5.10
