### ISSUE TITLE
Bt ranger dans menu in game

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#30]
**Describe the bug**
Le bt ranger dans le menu in game casse la physique des modules. Après avoir tap sur le bt ranger, des modules que je ne voyais pas avant ont bien respawn. Mais je ne pouvais plus interagir avec aucun module, aucune réaction au tap.

**
V0.12
iPhone 12 Pro

**Comment by Skeloson** [comment]
Le soucis vient de la pause qui n'était pas enlevée lorsque l'option ferme le menu. C'est réglé
