### ISSUE TITLE
Walter se tourne

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#31]
**Describe the bug**
Quand Walter se relève après la 1ere chute et regarde autour de lui avant de découvrir le joueur : on a toujours un pbl sur la façon dont il se tourne, il glisse sur le sol et ca saute entre chaque mvt, c'est pas une anim qui est joué. 

**Device:**
 - OS: iPhone 12 Pro
 - Build Version V0.12

**Comment by Skeloson** [comment]
Pourrais-tu envoyer un screencast, je ne suis pas sur de la partie de l'anim dont tu parle.

**Comment by angeliquesimonnet** [comment]
https://drive.google.com/file/d/1QJ6czpNdtj7Z7D1YkPBEPgyG5Vnh4GHN/view?usp=sharing

TC - 1min13
TC - 1min18
(à chaque fois qu'il se retourne en fait)

**Comment by Skeloson** [comment]
ça c'est l'animation de rotation. 
C'est aussi comme ça dans l'éditeur d'anim (je te ferai une vidéo du rendu dans l'éditeur demain, je n'ai pas de quoi enregistrer ici)
