### ISSUE TITLE
Pbl hold antenne petite tele 

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#32]
**Describe the bug**
C'est difficile d'attraper l'antenne de la petite télé avec les pubs (comme s'il n'y avait pas de zone de hold dessus) et l'antenne s'enfonce dans le sol aussi. Est-ce qu'il y a pas un pbl avec sa physique ?

**Screenshots/Screencast**
screenshot : https://drive.google.com/file/d/1LVyY5PH0WosmJhNXwu_lSMo-ZxAPgL7Z/view?usp=sharing

**Device:**
 - OS: iPhone 12 Pro
 - Build Version V0.12

**Comment by Skeloson** [comment]
Il n'y avait pas de collider sur l'antenne. C'est réglé.
