### ISSUE TITLE
Quand Walter recalcule son itinéraire, le son n'est pas coupé

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#33]
**Describe the bug**
Quand Walter recalcule son itinéraire, le son de marche continue alors que Walter ne se déplace pas

**Device:**
 - OS: iPhone12Pro
 - Build Version 0.12

**Comment by angeliquesimonnet** [comment]
V.0.12
iPhone 12Pro 
TC - 1min18
https://drive.google.com/file/d/1QJ6czpNdtj7Z7D1YkPBEPgyG5Vnh4GHN/view?usp=sharing

**Comment by Skeloson** [comment]
A retester dans la 0.5.13, je pense avoir résolu ça hier (à ce moment là en tout cas)
