### ISSUE TITLE
Condition de cadrage vortex 

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#34]
**Describe the bug**
On dirait que la condition de cadrage du vortex n'est plus en place ? Ou alors c'est que le timer de sonnerie du visiophone prend le dessus ? Le timer de sonnerie du visiophone doit etre lancé à partir du moment où Walter est évanouit. La condition pour qu'il s'évanouisse reste le cadrage du vortex. Si vraiment vous etes inquiet pour la demo parce qu'on a pas playtest le cadrage avec le son du vortex, on peut mettre un timer pour que Walter s'évanouisse quand même si on a pas cadré le vortex mais bon c'est moins logique.

**Device:**
 - OS: iPhone 12 Pro
 - Build Version V0.12

**Comment by Skeloson** [comment]
Le soucis du cadrage du vortex viens du fait que le vortex a été réduit, mais pas la zone à cadrer. 

C'est résolu.
