### ISSUE TITLE
Pbl de déplacement Walter et de comportement avec les modules.

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#39]
**Describe the bug**
Water bute un long moment dans un module sans que le pathfinding soit recalculé semble-t-il. Puis finalement il traverse le module. Pour aimanter à distance un module qui était hors de l'air de jeux.

Walter ne doit pas buter dans les modules
Walter ne doit pas traverser les modules
Les modules qui sont hors de l'air de jeux doivent respawn hors cadre dans l'air de jeu

**Screenshots/Screencast**
https://drive.google.com/file/d/1eeHbLQageFc7HNj8TmP4OBy9Mw7zcRcj/view?usp=sharing
TC - 14'08

**Device:**
 - OS: iPhone12Pro
 - Build Version 0.6.2

**Comment by Skeloson** [comment]
Besoin de plus d'information pour reproduire le bug.

Le système de respawn fonctionne bien, le module désiré est théoriquement encore dans l'air de jeu. De plus, Walter ne bouge pas tant que l'objet qu'il convoite ne bouge plus.

La collision répété avec la télé est un cas particulier, Walter ne pouvant pas l'éjecté devant lui vu qu'il y a des murs.

Enfin, Unity gère assez mal la collision entre les petits objets (pour Unity, des objets de 30 cm, c'est petit ^^'). On ne va pas pouvoir éviter que Walter traverse les objets quand il les coince de la sorte.
