### ISSUE TITLE
Pas de recalcul du pathfinding

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#42]
**Describe the bug**
Walter reste bloqué dans son déplacement, il est coincé par 2 modules 

**Screenshots/Screencast**
https://drive.google.com/file/d/1PNOGKi5UIiDHMokrWkTZpU7hxaR1Mk9j/view?usp=sharing
TC - 1'53 

**Device:**
 - OS: iPhone12Pro
 - Build Version 0.6.2

**Comment by Skeloson** [comment]
Ce cas de figure est un cas particulier : les deux objets sont des obstacles et Walter doit aller entre les 2 pour se cacher.
