### ISSUE TITLE
Les modules vibrent quand ils sont aimantés

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#43]
**Describe the bug**
Parfois quand les modules se mettent à léviter avant d'avancer vers l'aimant, ils sont agités d'une sorte de tremblement. C'est parce qu'ils entre en collision avec un autre module qui lévitent ? Dans ce cas il ne devrait pas tous lévité à la même hauteur peut-être ?

**Screenshots/Screencast**
https://drive.google.com/file/d/1PNOGKi5UIiDHMokrWkTZpU7hxaR1Mk9j/view?usp=sharing
TC - 4'07

**Device:**
 - OS: iPhone12Pro
 - Build Version 0.6.2

**Comment by Skeloson** [comment]
A retester dans une version avec l'aimant qui lévite

**Comment by angeliquesimonnet** [comment]
https://drive.google.com/file/d/1cNs6aGDwTSXlyFMAnHWRCrYIRQwSC9De/view?usp=sharing
TC - 5'20 
Ca le fait encore avec l'aimant en lévitation
