### ISSUE TITLE
Walter glisse sur le sol quand le visiophone sonne

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#44]
**Describe the bug**
Walter a glissé dans la position allongé avant de se relever

**Screenshots/Screencast**
https://drive.google.com/file/d/1PNOGKi5UIiDHMokrWkTZpU7hxaR1Mk9j/view?usp=sharing
TC - 4'25

**Device:**
 - OS: iPhone12Pro
 - Build Version 0.6.2

**Comment by Skeloson** [comment]
C'est fix.
