### ISSUE TITLE
Saute sur Walter quand il réagit au tap pendant une marche

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#45]
**Describe the bug**
Walter marche juste après que le visiophone ce soit refermé avant d'aller s'aseoir dans un coin contre le mur. Quand je lui tap dessus, il amorce u mouvement où il lève son bras mais il y a ne sorte de saute quand il revient en position initial pour marcher. 

**Screenshots/Screencast**
https://drive.google.com/file/d/1PNOGKi5UIiDHMokrWkTZpU7hxaR1Mk9j/view?usp=sharing
TC - 5'44

**Device:**
 - OS: iPhone12Pro
 - Build Version 0.6.2

**Comment by angeliquesimonnet** [comment]
Dans cette même marche il glisse parfois complétement aussi

**Comment by Skeloson** [comment]
Walter ne devrait plus glisser et les transitions entre ses animations a été améliorée pour la version 0.6.3
