### ISSUE TITLE
Cadrage Walter saute du fauteuil à la fin du clip

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#48]
**Describe the bug**
Je suis déjà cadré sur Walter et du coup au lieu de lancer l'anim puisqu'il est dans mon cadre, on dirait qu'il faut que je décadre et recadre

**Screenshots/Screencast**
https://drive.google.com/file/d/1cNs6aGDwTSXlyFMAnHWRCrYIRQwSC9De/view?usp=sharing
TC - 3'50

**Device:**
 - OS: iPhone 12Pro
 - Build Version 0.6.3

**Comment by Skeloson** [comment]
Ce problème est surement dû au fait que Walter est décalé de son pivot par l'animation (qui se trouve toujours devant le fauteuil) mais le collider qui gère la visibilité ne bouge pas, il est toujours au niveau du pivot.

Ce collider étant utilisé par les 3 états de Walter, il ne peut pas bouger du pivot.

Note, pour rebondir sur la tâche 254 "Walter saute du fauteuil et danse", que Walter ne pourras pas sauter au moment voulu si il faut le cadrer (vu que le joueur regardera la télé à ce moment là). Que fait-on ?
