### ISSUE TITLE
Bug tête de Walter levée pendant la marche 

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#49]
**Describe the bug**
Il y a un bug de Walter qui lève la tete (sans tap) et se rejoue pendant quelques secondes pendant les marches de Walter sans casque
On dirait que c'est parce qu'il lève la tete quand il rencontre un obstacle. Il faut plutot utiliser les idle de reaction sans lever la tete.

**Screenshots/Screencast**
https://drive.google.com/file/d/1cNs6aGDwTSXlyFMAnHWRCrYIRQwSC9De/view?usp=sharing
TC - 4secondes
TC - 4'54

**Device:**
 - OS: iPhone12Pro
 - Build Version 0.6.3

**Comment by Skeloson** [comment]
Fixer pour la V0.6.5
