### ISSUE TITLE
H&P : Walter est immobile

### ISSUE THREAD

**Issue by cguillaume44** [cguillaume44/WalterIssues#5]
Walter est immobile comme s'il ne savait pas quoi faire. Le jeu est comme bloqué et ne passe pas à la suite, il faut faire next.

iPhone 8 - Testflight 0.5(4) - Le 02/02/22 -
screencast https://drive.google.com/file/d/13m5qbIH9vwVcRlrYb1uRkCcpYz0YXLhW/view?usp=sharing
TC - 2min40

iPhone 8 - Testflight 0.5(4) - Le 02/02/22 -
screencast https://drive.google.com/file/d/19fGySKD39cOcd7FcujMTCiC0fQUldy7T/view?usp=sharing
TC - 3min55

**Comment by Skeloson** [comment]
Ce bug a normalement été fix depuis
