### ISSUE TITLE
Les bras de Walter sont bloqués dans une position, il ne peut pas passer à la suite

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#55]
**Describe the bug**
Walter se met dans une position bras tendu à la sortie du metal gear et il se met à courir avec les bras tendu jusqu'à l'échelle. Arriver à l'échelle il reste bloqué bras tendu et courant sur place. 

**Screenshots/Screencast**
https://drive.google.com/file/d/1TyBEWaHubFr1itL97NJIuflgoXsi9CGi/view?usp=sharing
TC - 3'53 

**Device:**
 - OS: iPhone 12 Pro
 - Build Version 0.6.5

**Comment by Skeloson** [comment]
C'est bizarre, l'animator de Walter s'est réinitialisé au moment où il est dans le vortex. 

A voir comment reproduire ce bug.

**Comment by Skeloson** [comment]
un fix a été trouvé, ça ne devrait plus se produire à partir de la 0.6.10
