### ISSUE TITLE
Quand le module TV tombe du transformateur le son du clip TV se relance

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#62]
**Describe the bug**
Quand le module TV tombe du transformateur dans sa face B poste de controle, le son du clip TV se relance

**Screenshots/Screencast**
https://drive.google.com/file/d/1hyp-Hms9-eUQfWRd0dsaGEu0a8YCjZ-d/view?usp=sharing
TC - 15'08

**Device:**
 - OS: iPhone12Pro
 - Build Version 0.6.5

**Comment by Skeloson** [comment]
fix pour la 0.6.7
