### ISSUE TITLE
Sortie du transformateur

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#64]
**Describe the bug**
La sortie du transformateur retombe au sol. 
L'animation se joue, le module se place. Mais quand on décadre et qu'on revient dessus, la sortie du transformateur n'est plus au plafond mais enfoncé dans le sol.

**Device:**
 - OS: iPhone 12 Pro
 - Build Version 0.6.6

**Comment by Skeloson** [comment]
un fix a été apporté, a retest dans la 0.6.8
