### ISSUE TITLE
Quand un module dont Walter a besoin est hold/magnet puis release, Walter n'avance pas direct vers le module

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#65]
**Describe the bug**
Walter regarde le joueur en attendant qu'il release le module (super!). Sauf que quand je release, Walter avance un peu vers le module puis se retrourne comme pour s'éloigner puis ré-avance pour prendre le module. Alors qu'il devrait s'avancer en un seul déplacement (directement, sinon on comprend pas que c'est ça ce qu'il voulait). 

**Screenshots/Screencast**
TC - 10'12
TC - 12'13 
https://drive.google.com/file/d/1fvnhgPryJrXCihFYPqvbhJl5RTvdTIb1/view?usp=sharing

**Device:**
 - OS: iPhone12Pro
 - Build Version 0.6.8

**Comment by Skeloson** [comment]
Problème trouvé et normalement fix, à tester dans la 0.6.10
