### ISSUE TITLE
Quand Walter se tourne pour pose un module, il baisse les bras 

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#66]
**Describe the bug**
Walter se tourne pour poser le visiophone mais il baisse les bras avant de se tourner donc on comprends pas trop, le visiophone lévite tout seul sans la magnétisation des ventouses de Walter. Il faut qu'il ait toujours les bras tendus quand il pivote

**Screenshots/Screencast**
https://drive.google.com/file/d/1W3UUqyczaQaqO7h24S44j8lihPImywkZ/view?usp=sharing
TC - 4'03

**Device:**
 - OS: iPhone 12Pro
 - Build Version 0.6.8

**Comment by Skeloson** [comment]
Walter n'a pas d'autre animation que courir quand il a un module en main. Dans le cas présent, il est passé en idle standard car il ne se déplace plus.

-> à voir coté anim

**Comment by angeliquesimonnet** [comment]
Tu peux faire pivoter Walter en utilisant la course/marche avec un module (comme on avait testé de le faire pivoter en utilisant son anim de marche)
