### ISSUE TITLE
Walter court sur place avant de poser le module

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#67]
**Describe the bug**
Walter arrive sous le vortex avec l'échelle mais le visiophone derrière semble le gêner pour poser donc il continue de courir sur plce avant de poser l'échelle. Il devrait poser directement l'échelle et si le visiophone gêne ca le décale/repousse au moment où l'échelle est posée. 

**Screenshots/Screencast**
https://drive.google.com/file/d/1W3UUqyczaQaqO7h24S44j8lihPImywkZ/view?usp=sharing
TC - 2'51

**Device:**
 - OS: iPhone12Pro
 - Build VersionV.0.6.8

**Comment by Skeloson** [comment]
Walter n'a pas d'autre animation que courir quand il a un module en main. Dans le cas présent, il est rester en course avec module car il n'a pas d'anim pour se tourner avec un module.

-> à voir coté anim
