### ISSUE TITLE
Respawn automatique hors cadre ne fonctionne pas

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#7]
iphone 12 pro 
build V 0.5.5

**Comment by Skeloson** [comment]
Quel est ta position par rapport à l'air de jeu ?

**Comment by angeliquesimonnet** [comment]
https://drive.google.com/file/d/1D_bc5ItPwCu7afZ09PJ1KMDWxNu7puo_/view?usp=sharing
TC - 14min 
J'ai le module receptacle 01, quand j'essaye de le mettre dans la machine il est ejecté. Puis impossible de le retrouver, même avec le respawner d'ailleurs. Je cherche jusque dans le couloir (peut-être qu'il est dans le mur puisque la sortie du transformateur c'est mise dans le mur donc la zone doit etre mal detectée mais il devrait quand même revenir à proximité du respawner quand je l'utilise donc re-rentrer dans une zone accessible à ma vision)
