### ISSUE TITLE
Reglage de l'antenne - Hold possible une seule fois

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#8]
On ne peut hold&swipe qu'une seule fois l'antenne. Après l'avoir hold une première fois si j'ai release et que je veux de nouveau hold je ne peux plus hold, il ne se passe rien quand j'ai mon doigt dessus. 

Build V0.5.5
iPhone 12 pro

**Comment by Skeloson** [comment]
Serait-il possible d'avoir un screencast ? 
Le seul que j'ai vu montrais une utilisation correcte de l'antenne

**Comment by angeliquesimonnet** [comment]
https://drive.google.com/file/d/1D_bc5ItPwCu7afZ09PJ1KMDWxNu7puo_/view?usp=sharing
TC - 10min30 (je hold une fois, et ensuite je réessaye plusieurs fois sans résultat. Je dois faire next pour passer à la suite)
