### ISSUE TITLE
Zone de noir dans les modèles

### ISSUE THREAD

**Issue by angeliquesimonnet** [cguillaume44/WalterIssues#9]
On dirait que la zone dans laquelle l'écran devient noir quand on s'approche des modèles est plus grande que juste l'intérieur du modèle. Mon écran devient noir dès que j'approche trop près alors que je ne suis pas dedans il me semble. 

Build V 0.5.5
iPhone 12 pro

**Comment by Skeloson** [comment]
la zone de détection sur la camera a été réduite, à tester.
